name: Upload results to Datadog
if: always()
inputs:
  api-key:
    description: "Datadog API key"
    required: true
runs:
  using: "composite"
  steps:
    # The npm install was taking 30s to 1m, accounting for 20+% of the total
    # job time.
    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: "**/node_modules"
        key: datadog-ci-${{ runner.os }}
        restore-keys: |
          datadog-ci-
    - shell: bash
      run: |
        owner=${{ github.repository_owner	}}
        echo "owner: $owner"

        if [[  $owner != "coder" ]]; then
          echo "Not a pull request from the main repo, skipping..."
          exit 0
        fi
        if [[ -z "${{ inputs.api-key }}" ]]; then
          # This can happen for dependabot.
          echo "No API key provided, skipping..."
          exit 0
        fi

        npm install @datadog/datadog-ci@2.10.0
        npm x datadog-ci -- junit upload --service coder ./gotests.xml \
          --tags os:${{runner.os}} --tags runner_name:${{runner.name}}

        # Debugging:
        ls -al
        pwd
      env:
        DATADOG_API_KEY: ${{ inputs.api-key }}
